In [1]:
from model import *
from pde import *
from derivative import *
from residual import *

In [2]:
key = jax.random.PRNGKey(123)
model = PINN(key)
d = Derivative()

In [3]:
x = jnp.arange(10)/10.0
t = jnp.arange(10)/10.0

In [4]:
d.phi(model,x,t)

Array([0.26176221, 0.2622055 , 0.26260259, 0.26295337, 0.26326489,
       0.26355026, 0.26382633, 0.26411083, 0.26441964, 0.26476475],      dtype=float64)

In [5]:
d.phi(model,1,t)

Array([0.28754603, 0.28555064, 0.28347884, 0.2813346 , 0.27912441,
       0.27685736, 0.27454513, 0.27220177, 0.26984341, 0.2674877 ],      dtype=float64)

In [6]:
d.phi(model,x,1)

Array([0.23462789, 0.23788314, 0.24112048, 0.24432626, 0.24748872,
       0.25059823, 0.25364741, 0.25663087, 0.25954478, 0.26238633],      dtype=float64)

In [7]:
d.phi(model,1,1)

Array(0.26515321, dtype=float64)

In [9]:
d.evaluate(model,x,t,['phi','c','phi_t','phi_x','phi_2x','c_t','c_x','c_2x'])

{'phi': Array([0.26176221, 0.2622055 , 0.26260259, 0.26295337, 0.26326489,
        0.26355026, 0.26382633, 0.26411083, 0.26441964, 0.26476475],      dtype=float64),
 'c': Array([-0.03540194, -0.03861464, -0.04206976, -0.04564288, -0.04922042,
        -0.05270728, -0.05603095, -0.05914191, -0.06201156, -0.0646285 ],      dtype=float64),
 'phi_t': Array([-0.02954998, -0.02915039, -0.02870908, -0.02821688, -0.02766323,
        -0.02704145, -0.02635198, -0.02560338, -0.02481112, -0.02399496],      dtype=float64),
 'phi_x': Array([0.03419634, 0.03335839, 0.03244256, 0.031511  , 0.03062177,
        0.02981882, 0.02912602, 0.02854622, 0.02806468, 0.02765535],      dtype=float64),
 'phi_2x': Array([-0.01256258, -0.01369042, -0.01424319, -0.0142135 , -0.0136764 ,
        -0.01276878, -0.0116555 , -0.01049373, -0.00940564, -0.00846482],      dtype=float64),
 'c_t': Array([0.02559289, 0.02426503, 0.02310659, 0.02211205, 0.02125813,
        0.02051365, 0.01984779, 0.01923528, 0.01865869, 0.0181082